# Development-specific parameters for exampleSite

[modules.hinode.csp]
    frame-src = [
        "http:",                         # Allow all HTTP sources for local development
        "https:",
        "*.googletagmanager.com",
        "player.cloudinary.com",
        "www.youtube-nocookie.com",
        "www.youtube.com",
        "player.vimeo.com"
    ]
