# toml-docs-start lang-main
[en]
    languageName = "English"
    contentDir = "content/en"
    weight = 1
# toml-docs-end lang-main
# toml-docs-start lang-param
    [en.params.head]
        tagline = "an everything site"
    [en.params.feature]
        link = "/en/blog"
        caption = "Fig About it"
    [en.params.footer]
        license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank'>CC BY-NC-SA 4.0</a>)."
        socialTitle = "Follow us"
        socialCaption = "We do tech, subcuture, relearn the ready known"
# toml-docs-end lang-param

[nl]
    languageName = "Nederlands"
    contentDir = "content/nl"
    weight = 2
    [nl.params.head]
        tagline = "an everything site"
    [nl.params.feature]
        link = "/en/about"
        caption = "About"
    [nl.params.footer]
        license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank'>CC BY-NC-SA 4.0</a>)."
        socialTitle = "Follow us"
        socialCaption = "We do tech, subcuture, relearn the ready known"