[module]
  hugoVersion.extended = true
  hugoVersion.min = '0.146.0'
  # expose bookshop partials to Hugo
  [[module.mounts]]
    source = '.'
    target = 'layouts/partials/bookshop' # note: bookshop engine 3.17.1 does not recognize layouts/_partials/bookshop yet
    includeFiles = [
      '**/*.hugo.html',
    ]
  # expose bookshop specifications as Hinode data structure
  [[module.mounts]]
    source = '.'
    target = 'data/structures'
    includeFiles = ['**/*.bookshop.yml']
  # integrate main bookshop style with Hinode styles pipeline
  [[module.mounts]]
    source = 'bookshop.scss'
    target = 'assets/scss/bookshop.scss'
  # integrate bookshop component styles with Hinode styles pipeline
  [[module.mounts]]
    source = '.'
    target = 'assets/scss/modules/bookshop'
    includeFiles = ['**/*.scss']
    excludeFiles = ['bookshop.scss']
