[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 20

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/"
  weight = 20

[[social]]
  name = "Medium"
  pre = "fab medium"
  url = "https://medium.com/"
  weight = 30
