[[main]]
  name = "Over mij"
  url = "/over-mij/"
  weight = 10

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[[main]]
  name = "Projecten"
  url = "/projecten/"
  weight = 30

[[main]]
  name = "Voorbeeldproject"
  url = "/nl/projecten/voorbeeldproject/"
  parent = "Projecten"
  weight = 1

[[main]]
  name = "Ander project"
  url = "/nl/projecten/ander-project/"
  parent = "Projecten"
  weight = 2

[[main]]
  name = "Tags"
  url = "/tags/"
  weight = 40

[[social]]
  name = "LinkedIn"
  pre = "<i class=\"fab fa-linkedin fa-2x\"></i>"
  url = "https://linkedin.com/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "<i class=\"fab fa-github fa-2x\"></i>"
  url = "https://github.com/"
  weight = 20

[[social]]
  name = "Medium"
  pre = "<i class=\"fab fa-medium fa-2x\"></i>"
  url = "https://medium.com/"
  weight = 30